services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    depends_on:
      - db 
    environment:
      - HTTPX_TIMEOUT=30.0
      - BACKEND_URL=http://localhost:8001
      - DATABASE_URL=postgresql+psycopg2://ciberpunk:ciberpunk123@db:5432/ciberpunkdb 
    volumes:
      - ./data:/data
    networks:
      app_net:
        ipv4_address: 172.80.0.200
    #dns:
    #  - 8.8.8.8
    #  - 1.1.1.1
    #environment:
    #  
    #extra_hosts:
    #  - "accounts.google.com:142.250.200.45"  # IP de Google (cambia según región)


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - backend
    networks:
      app_net:
        ipv4_address: 172.80.0.100
    #dns:
    #  - 8.8.8.8
    #  - 1.1.1.1
    extra_hosts:
      - "www.gravatar.com:172.67.136.25"  # IP actual de Gravatar

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ciberpunk
      POSTGRES_PASSWORD: ciberpunk123
      POSTGRES_DB: ciberpunkdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    networks:
      app_net:
        ipv4_address: 172.80.0.150


volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
    internal: true 
    ipam:
      config:
        - subnet: 172.80.0.0/16