version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    environment:
      #- BACKEND_URL=http://localhost:8001  # Usar nombre de servicio
    networks:
      app_net:
        ipv4_address: 172.80.0.200

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  # Mapeo correcto: host:8282 → contenedor:3000
    environment:
      #- NEXT_PUBLIC_API_URL=/api  # Ruta relativa
      #- HOST=0.0.0.0
      #- PORT=3000
    depends_on:
      - backend
    networks:
      app_net:
        ipv4_address: 172.80.0.100

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16







