version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    depends_on:
      - db 
    environment:
      - BACKEND_URL=http://localhost:8001
    volumes:
      - ./data:/data
    networks:
      app_net:
        ipv4_address: 172.80.0.200


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - backend
    networks:
      app_net:
        ipv4_address: 172.80.0.100

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ciberpunk
      POSTGRES_PASSWORD: ciberpunk123
      POSTGRES_DB: ciberpunkdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    networks:
      app_net:
        ipv4_address: 172.80.0.150


volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16
