version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - ALEMBIC_CONFIG=/app/alembic.ini
      - BACKEND_URL=http://localhost:8001
      - DATABASE_URL=postgresql://ciberpunk:ciberpunk123@db:5432/ciberpunkdb

    volumes:
      - ./data:/data
      - ./backend:/app  # Cambio crucial
      - ./backend/alembic:/app/alembic  # Monta el directorio de migraciones
      - ./backend/alembic.ini:/app/alembic.ini  # Monta el archivo de configuración
    networks:
      app_net:
        ipv4_address: 172.80.0.200
    # Comando para ejecutar migraciones al iniciar (opcional)
    # command: sh -c "alembic upgrade head && python main.py"  # Ajusta según tu estructura

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - backend
    networks:
      app_net:
        ipv4_address: 172.80.0.100

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ciberpunk
      POSTGRES_PASSWORD: ciberpunk123
      POSTGRES_DB: ciberpunkdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - ./backups:/backups  # Volumen para backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciberpunk -d ciberpunkdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      app_net:
        ipv4_address: 172.80.0.150

volumes:
  postgres_data:
  # alembic_migrations:  # Volumen opcional para migraciones si no quieres montar el directorio local

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16