# traefik.yml (Balanceador)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      middlewares:
        - modsecurity@file

http:
  middlewares:
    modsecurity:
      plugin:
        modsecurity:
          rules: |
            SecRuleEngine On
            SecRequestBodyAccess On
            SecRule REQUEST_HEADERS:Content-Type "text/xml" "id:'200000',phase:1,t:none,t:lowercase,pass,nolog,ctl:requestBodyProcessor=XML"
            Include @owasp_crs/*.conf