"""add_status_to_users

Revision ID: 2a827de0e060
Revises: c0783b41797d
Create Date: 2025-07-31 13:32:34.166199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a827de0e060'
down_revision: Union[str, None] = 'c0783b41797d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('active', 'suspended', name='userstatus'), nullable=True))
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', postgresql.ENUM('free', 'pro', 'business', 'enterprise', name='subscriptionplan'), autoincrement=False, nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
