"""Descripción de los cambios

Revision ID: d5cc360d25f1
Revises: 80e59143ef16
Create Date: 2025-07-06 12:52:20.224293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5cc360d25f1'
down_revision: Union[str, None] = '80e59143ef16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'subscriptions', ['user_id'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', sa.VARCHAR(length=10), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
