"""Descripción de los cambios

Revision ID: e5d97a9854d8
Revises: ec8315483c7d
Create Date: 2025-07-06 11:59:39.476646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d97a9854d8'
down_revision: Union[str, None] = 'ec8315483c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription', sa.Enum('free', 'pro', 'business', 'enterprise', name='subscriptionplan'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription')
    # ### end Alembic commands ###
